<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_17 Des 2022 - 21.08PAIDYogaManeRp 200.0_418ef3</name>
   <tag></tag>
   <elementGuidId>c1ead054-86f3-4b59-9c79-36911ada6eab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[7]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7adb1f4e-7117-4866-b2f9-616593990585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative h-full rounded-20 border bg-white py-4 shadow-4</value>
      <webElementGuid>de3d7799-de1b-4bd8-aa34-e33c8fe85a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>17 Des 2022 - 21.08PAIDYogaManeRp 200.000Roma Donaroma123@gmail.comSunday (09:00 - 11:00); Wednesday (13:00 - 15:00); Friday (14:00 - 18:00); </value>
      <webElementGuid>00f4a580-de93-471a-beeb-80f7d167ebaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 sm:pl-52 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 md:grid-cols-2 md:gap-6 xl:grid-cols-2 2xl:grid-cols-3&quot;]/div[7]/div[@class=&quot;relative h-full rounded-20 border bg-white py-4 shadow-4&quot;]</value>
      <webElementGuid>865c07dd-a5c1-4ac5-b9a9-33b7068ce5ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[7]/div</value>
      <webElementGuid>f86bd5ed-213d-4756-8041-f188f5b14d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yoga'])[4]/following::div[14]</value>
      <webElementGuid>7a6ef81b-66ec-4b04-b405-ea11246b67e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAID'])[2]/following::div[18]</value>
      <webElementGuid>a09f7a52-d6e0-470c-9fa2-37e4250b2d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div</value>
      <webElementGuid>a46092f6-b9d7-4ba3-96a8-dd373f952a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '17 Des 2022 - 21.08PAIDYogaManeRp 200.000Roma Donaroma123@gmail.comSunday (09:00 - 11:00); Wednesday (13:00 - 15:00); Friday (14:00 - 18:00); ' or . = '17 Des 2022 - 21.08PAIDYogaManeRp 200.000Roma Donaroma123@gmail.comSunday (09:00 - 11:00); Wednesday (13:00 - 15:00); Friday (14:00 - 18:00); ')]</value>
      <webElementGuid>f2d27a2e-60e5-42ac-a3f4-7efbd7569488</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
