<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EditRp 150.000Sunday (0900 - 1100)Wedne_e5d352</name>
   <tag></tag>
   <elementGuidId>3d6bbe42-e96b-4b4a-83f9-1520dc3aea0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>55e61556-7889-40ed-bdc0-55c7a6f15acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-5</value>
      <webElementGuid>37c6956c-fd2e-41fc-a656-c40b6dcd31e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EditRp 150.000Sunday (09:00 - 11:00)Wednesday (13:00 - 15:00)Friday (14:00 - 18:00)Mane Mane Mane</value>
      <webElementGuid>722f99cb-cf48-4af7-acde-4e787c52b625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[1]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 sm:grid-cols-2 md:grid-cols-2 md:gap-6 xl:grid-cols-3 2xl:grid-cols-4&quot;]/div[@class=&quot;rounded-20 bg-white shadow-3&quot;]/div[@class=&quot;p-5&quot;]</value>
      <webElementGuid>41101a97-3b75-4072-9345-7daada4543aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>388b06b9-7479-42df-8db1-c6a0bf3a7843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddNewd'])[1]/following::div[7]</value>
      <webElementGuid>2142e696-b79c-473d-a727-3853e525dbf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zumba'])[1]/following::div[7]</value>
      <webElementGuid>696c0cff-f4a7-413c-9bf6-5081a4244588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>592b5fec-c42b-4580-9f0b-9bb12c35626a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'EditRp 150.000Sunday (09:00 - 11:00)Wednesday (13:00 - 15:00)Friday (14:00 - 18:00)Mane Mane Mane' or . = 'EditRp 150.000Sunday (09:00 - 11:00)Wednesday (13:00 - 15:00)Friday (14:00 - 18:00)Mane Mane Mane')]</value>
      <webElementGuid>cc8061e5-a999-494b-9cc3-c06b6ec3fb7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
