<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pull UpRp 24.000Sunday (0900 - 1100)Wed_860b0f</name>
   <tag></tag>
   <elementGuidId>326b0385-95a6-4c84-89e4-52b5576702c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>edb8671a-5682-460a-a073-cfe0bbe6e91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-5</value>
      <webElementGuid>2eca7d2c-b4c8-4bfc-8278-93258309ebd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pull UpRp 24.000Sunday (09:00 - 11:00)Wednesday (13:00 - 15:00)Friday, 14:00 - 18:00Mane</value>
      <webElementGuid>802f47a1-584f-4c52-a5b2-969f8f9d0066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[1]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 sm:grid-cols-2 md:grid-cols-2 md:gap-6 xl:grid-cols-3 2xl:grid-cols-4&quot;]/div[@class=&quot;rounded-20 bg-white shadow-3&quot;]/div[@class=&quot;p-5&quot;]</value>
      <webElementGuid>1fb843f6-b39d-4a36-b8d3-2e8021282294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>d5189a2c-bda7-4563-b8c3-bf3d898779cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddNewd'])[1]/following::div[7]</value>
      <webElementGuid>fbb1a541-2679-4dda-a1f3-b9814a2e2a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zumba'])[1]/following::div[7]</value>
      <webElementGuid>95a277b8-897c-464e-b278-b083347de5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>4071c889-aec0-4f64-afdd-733466925cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pull UpRp 24.000Sunday (09:00 - 11:00)Wednesday (13:00 - 15:00)Friday, 14:00 - 18:00Mane' or . = 'Pull UpRp 24.000Sunday (09:00 - 11:00)Wednesday (13:00 - 15:00)Friday, 14:00 - 18:00Mane')]</value>
      <webElementGuid>3ae81e53-943f-4884-8a60-6d924be1b4b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
