<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Saved</name>
   <tag></tag>
   <elementGuidId>8b9218f6-0123-48da-ad64-62ebed8a0d0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#swal2-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='swal2-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>6e1f6207-5eb0-4166-a855-588e255c3538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-title</value>
      <webElementGuid>2c354226-a11b-4cb9-823f-f528ece1e0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swal2-title</value>
      <webElementGuid>c22b0aba-ab78-4db4-ab22-5148f9f15304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saved</value>
      <webElementGuid>f52f74ef-ce98-44c0-a6d0-ce5e2d3d31be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-title&quot;)</value>
      <webElementGuid>6fb7d324-2b1d-470d-aaf5-5ed2d5b75492</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='swal2-title']</value>
      <webElementGuid>efce319c-6021-4523-9cd6-b00ec16bf72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::h2[1]</value>
      <webElementGuid>b1915334-7c72-4393-878d-a3af8a694429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'swal2-title', '&quot;', ')')])[1]/following::h2[1]</value>
      <webElementGuid>3e67b8cb-d2c7-4fe6-865e-ed07e0176567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offline classes data successfully saved'])[1]/preceding::h2[1]</value>
      <webElementGuid>0a68ff84-34bc-43c0-8fcb-9aeb05053c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::h2[1]</value>
      <webElementGuid>3a0c668d-c09d-4984-834a-ca165424995a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saved']/parent::*</value>
      <webElementGuid>965698a8-fcd1-47a0-bd34-3a4db67058b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h2</value>
      <webElementGuid>1725ae4b-002c-40d7-bad1-b808b5d28c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'swal2-title' and (text() = 'Saved' or . = 'Saved')]</value>
      <webElementGuid>eafeb1c2-549e-4551-8314-e874ff90ddb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
