<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sunday (0900 - 1100)_absolute inset-0 h_a6d7ed</name>
   <tag></tag>
   <elementGuidId>73911f77-e1d2-439c-b7a2-cb6aae4bd1b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div[7]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cc9b7536-338a-48ab-baf6-22233f4c430f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 h-full w-full rounded-t-20 object-cover object-center transition duration-300 ease-in-out hover:scale-105 hover:rounded-t-20</value>
      <webElementGuid>1cdcf7dd-7ca3-4891-a167-90b15bb24036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/alterra-capstone.appspot.com/workouts/039d2d1b0eb949fcb5852034888db4e8.png?Expires=1703071526&amp;GoogleAccessId=firebase-adminsdk-kae8m%40alterra-capstone.iam.gserviceaccount.com&amp;Signature=ds4nuVLx7Rv9TurnaxOH2ZMS4zRZ6F1lGBUPZDFpSIcDhOQVGfOfSa80Sgi4ke7R50T51z%2FcDTP8tRsOq0AAWMpoNP+HyOG6DRCuDzgKcl1SaMs%2F75RJpQYwG49uZBFALDBw1Zi4NFm5dq3a+veNRXJYGucFcyp6Pt+L2AO9+SdEiEII4ce7GqkdYgu8TV3Ty3SdUtxqOamnGlSVewGNZq7J%2F6XzWorLBZ9QTeY0ZjLg62txYxSjGcwMKPcPBsRJ8D5JAp+C1sJlo42tnUFVQL5NtNw5LPUh8HP4GUC78%2FGaxBnGQpXiFiIZA9yqhGiXI8WJ%2FpEYX7kmBJp1kVRFaA%3D%3D</value>
      <webElementGuid>eb368f56-da09-4a76-9951-339377691597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>workout-image</value>
      <webElementGuid>87188bc0-944a-4a1e-a973-95404dfe3e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>3db163b6-081f-405a-8d6e-bb9e14ee713e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[1]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 sm:grid-cols-2 md:grid-cols-2 md:gap-6 xl:grid-cols-3 2xl:grid-cols-4&quot;]/div[@class=&quot;rounded-20 bg-white shadow-3&quot;]/div[@class=&quot;relative overflow-hidden rounded-t-20 pb-40&quot;]/img[@class=&quot;absolute inset-0 h-full w-full rounded-t-20 object-cover object-center transition duration-300 ease-in-out hover:scale-105 hover:rounded-t-20&quot;]</value>
      <webElementGuid>a70837b4-863b-4512-bd78-eef27a64c983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div[7]/div/img</value>
      <webElementGuid>611fdd4f-4879-41b4-8e0f-1c4d84612be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='workout-image'])[7]</value>
      <webElementGuid>deb165ab-ee15-4714-af2c-be631bd55fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/img</value>
      <webElementGuid>f00c3543-bdf6-4a1a-8268-785e2226b1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/alterra-capstone.appspot.com/workouts/039d2d1b0eb949fcb5852034888db4e8.png?Expires=1703071526&amp;GoogleAccessId=firebase-adminsdk-kae8m%40alterra-capstone.iam.gserviceaccount.com&amp;Signature=ds4nuVLx7Rv9TurnaxOH2ZMS4zRZ6F1lGBUPZDFpSIcDhOQVGfOfSa80Sgi4ke7R50T51z%2FcDTP8tRsOq0AAWMpoNP+HyOG6DRCuDzgKcl1SaMs%2F75RJpQYwG49uZBFALDBw1Zi4NFm5dq3a+veNRXJYGucFcyp6Pt+L2AO9+SdEiEII4ce7GqkdYgu8TV3Ty3SdUtxqOamnGlSVewGNZq7J%2F6XzWorLBZ9QTeY0ZjLg62txYxSjGcwMKPcPBsRJ8D5JAp+C1sJlo42tnUFVQL5NtNw5LPUh8HP4GUC78%2FGaxBnGQpXiFiIZA9yqhGiXI8WJ%2FpEYX7kmBJp1kVRFaA%3D%3D' and @alt = 'workout-image']</value>
      <webElementGuid>bbd22167-2013-429f-a050-4fb519eb6b29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
