<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Yoga_absolute inset-0 h-full w-full rou_26285e</name>
   <tag></tag>
   <elementGuidId>bcdb3f7b-d32c-4b50-be45-364a261663cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a9ff8e76-0bf4-475e-8970-2a3921cbb030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 h-full w-full rounded-t-20 object-cover object-center transition duration-300 ease-in-out hover:scale-105 hover:rounded-t-20</value>
      <webElementGuid>81410950-3488-4cd9-96b8-ef912fed28f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/alterra-capstone.appspot.com/workouts/88bec4438d1c46888f6c58ee74a8b18b.jpg?Expires=1702634335&amp;GoogleAccessId=firebase-adminsdk-kae8m%40alterra-capstone.iam.gserviceaccount.com&amp;Signature=HA3Cqan5c1pjKzsx3R81Cyj%2FLtiuaglpoAbrtPEAejG8y61NBYOSO2cmHQw58n0uV+vjOSLLT3B4ZlZEkVB4wGG7oADTEKk20FFHaVAl3J+65ttyA5%2FpUx0IxC1RxaGEv+3CIgFe7LkgJS4hCc2oeeY1uMt2QhIRAbat2PmxFCeob%2FeCLLwoBp0F8tnKW6snf%2FzO7bmNxxW+9kExEuXerSbJMWx3Oym4bfXO99nVC%2FAzZRrWUJC9SjKK9rbGHxYlst9LFJWcrNVbjwpXCl3PNEBhJ0TuhSAbJ5CBPmhi6q3yF74zS7XrpckIl5CX7AdkugFCocdC2TDGWR7eN%2FKOMA%3D%3D</value>
      <webElementGuid>b5400f7d-df90-4ed0-999d-9aacc66c24e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>workout-image</value>
      <webElementGuid>a3a435d2-a3de-4bd0-9ed8-66ae93bec32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>149e5de8-6a1e-417a-9118-c621f288d778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 sm:pl-52 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[1]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 md:grid-cols-2 md:gap-6 xl:grid-cols-3 2xl:grid-cols-4&quot;]/div[@class=&quot;rounded-20 bg-white shadow-3&quot;]/div[@class=&quot;relative overflow-hidden rounded-t-20 pb-40&quot;]/img[@class=&quot;absolute inset-0 h-full w-full rounded-t-20 object-cover object-center transition duration-300 ease-in-out hover:scale-105 hover:rounded-t-20&quot;]</value>
      <webElementGuid>807820a0-5df3-4860-aed2-a90e2d91112c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>10a59775-b098-4ce5-9ad3-ad849d775b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 h-full w-full rounded-t-20 object-cover object-center transition duration-300 ease-in-out hover:scale-105 hover:rounded-t-20</value>
      <webElementGuid>4be8f944-928a-48dc-809c-80ead049f179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/alterra-capstone.appspot.com/workouts/88bec4438d1c46888f6c58ee74a8b18b.jpg?Expires=1702634335&amp;GoogleAccessId=firebase-adminsdk-kae8m%40alterra-capstone.iam.gserviceaccount.com&amp;Signature=HA3Cqan5c1pjKzsx3R81Cyj%2FLtiuaglpoAbrtPEAejG8y61NBYOSO2cmHQw58n0uV+vjOSLLT3B4ZlZEkVB4wGG7oADTEKk20FFHaVAl3J+65ttyA5%2FpUx0IxC1RxaGEv+3CIgFe7LkgJS4hCc2oeeY1uMt2QhIRAbat2PmxFCeob%2FeCLLwoBp0F8tnKW6snf%2FzO7bmNxxW+9kExEuXerSbJMWx3Oym4bfXO99nVC%2FAzZRrWUJC9SjKK9rbGHxYlst9LFJWcrNVbjwpXCl3PNEBhJ0TuhSAbJ5CBPmhi6q3yF74zS7XrpckIl5CX7AdkugFCocdC2TDGWR7eN%2FKOMA%3D%3D</value>
      <webElementGuid>f61533e6-965e-4e5a-89c1-89d0c9b053e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>workout-image</value>
      <webElementGuid>5491dae2-8f8c-453e-b644-a0750ca15cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>fa0a1cee-63cf-4892-806a-10f1a2750e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 sm:pl-52 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[1]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 md:grid-cols-2 md:gap-6 xl:grid-cols-3 2xl:grid-cols-4&quot;]/div[@class=&quot;rounded-20 bg-white shadow-3&quot;]/div[@class=&quot;relative overflow-hidden rounded-t-20 pb-40&quot;]/img[@class=&quot;absolute inset-0 h-full w-full rounded-t-20 object-cover object-center transition duration-300 ease-in-out hover:scale-105 hover:rounded-t-20&quot;]</value>
      <webElementGuid>3460c0ff-c854-44af-a84e-21c2da8b801e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/img</value>
      <webElementGuid>4dcba560-911a-4c72-8139-cd6025405bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='workout-image']</value>
      <webElementGuid>f798271f-d43f-4f18-8a3f-fe57928e1e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d63d1710-3a2d-4c3a-9c47-1435e383e84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/alterra-capstone.appspot.com/workouts/88bec4438d1c46888f6c58ee74a8b18b.jpg?Expires=1702634335&amp;GoogleAccessId=firebase-adminsdk-kae8m%40alterra-capstone.iam.gserviceaccount.com&amp;Signature=HA3Cqan5c1pjKzsx3R81Cyj%2FLtiuaglpoAbrtPEAejG8y61NBYOSO2cmHQw58n0uV+vjOSLLT3B4ZlZEkVB4wGG7oADTEKk20FFHaVAl3J+65ttyA5%2FpUx0IxC1RxaGEv+3CIgFe7LkgJS4hCc2oeeY1uMt2QhIRAbat2PmxFCeob%2FeCLLwoBp0F8tnKW6snf%2FzO7bmNxxW+9kExEuXerSbJMWx3Oym4bfXO99nVC%2FAzZRrWUJC9SjKK9rbGHxYlst9LFJWcrNVbjwpXCl3PNEBhJ0TuhSAbJ5CBPmhi6q3yF74zS7XrpckIl5CX7AdkugFCocdC2TDGWR7eN%2FKOMA%3D%3D' and @alt = 'workout-image']</value>
      <webElementGuid>e6d8a4b6-fe50-403b-ac1d-80d501652c54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
