<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Senin_absolute inset-0 h-full w-full ro_261936</name>
   <tag></tag>
   <elementGuidId>82afb310-59aa-4380-8a9e-ec094f4b10f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>50692794-d7f3-4d26-b59d-174a445da1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 h-full w-full rounded-t-20 object-cover object-center transition duration-300 ease-in-out hover:scale-105 hover:rounded-t-20</value>
      <webElementGuid>e2057f9e-41da-403d-a0eb-d8f93b088d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/clean-code-72e8f.appspot.com/workouts/7f287478c71442cbb6fb2f906ba93d9f.jpeg?Expires=1702712444&amp;GoogleAccessId=firebase-adminsdk-lenaf%40clean-code-72e8f.iam.gserviceaccount.com&amp;Signature=ii3cyIrc28suASq%2FrRX4hAffmFEMAbXEVEdLFqO%2FzO526onfLLdZQrIlQ2vfbgw%2Fhsr1We4C8IexkJRbpnuDztvXrJrsw2nnd7RzXsX6gXSrZZWMJdXIcSGj3aqb%2FwfWam9AjvPtQKSoyCftP3P%2FkGP+U6gPe8KpIvCfS5MSYx36gkVwW5MPxkkqk%2FTFas2aNCG1OARQQgCsrk3GQOv0htmg2TFVbwhYZlUvbL7SJAZlaehS0y65YVraSx4LEfIbBsaUi+ozXe+U8vNCuqZGpdqJKXSxUOvKBI%2F082P32zZumE2THawJxlbXepWpOn5FNFRaW7vktgm1aIfp%2F7L3yg%3D%3D</value>
      <webElementGuid>4eafc778-c983-4305-bdf0-79e5d335d1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>workout-image</value>
      <webElementGuid>96b9f42b-6add-4d2b-a4f2-09c63eb509ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>009d0715-4047-41c7-91bd-42c8b5b9ea93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 sm:pl-52 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[1]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 md:grid-cols-2 md:gap-6 xl:grid-cols-3 2xl:grid-cols-4&quot;]/div[@class=&quot;rounded-20 bg-white shadow-3&quot;]/div[@class=&quot;relative overflow-hidden rounded-t-20 pb-40&quot;]/img[@class=&quot;absolute inset-0 h-full w-full rounded-t-20 object-cover object-center transition duration-300 ease-in-out hover:scale-105 hover:rounded-t-20&quot;]</value>
      <webElementGuid>0d157998-8cf3-47ea-9d74-d8a7ceb82b87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div[2]/div/img</value>
      <webElementGuid>1daf1f4a-9713-44a6-ac28-2a24f77428ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='workout-image'])[2]</value>
      <webElementGuid>d15bfc25-e467-448d-8cbd-d84cf210314c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>c34b2233-7200-48a5-8e32-31b32529a593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/clean-code-72e8f.appspot.com/workouts/7f287478c71442cbb6fb2f906ba93d9f.jpeg?Expires=1702712444&amp;GoogleAccessId=firebase-adminsdk-lenaf%40clean-code-72e8f.iam.gserviceaccount.com&amp;Signature=ii3cyIrc28suASq%2FrRX4hAffmFEMAbXEVEdLFqO%2FzO526onfLLdZQrIlQ2vfbgw%2Fhsr1We4C8IexkJRbpnuDztvXrJrsw2nnd7RzXsX6gXSrZZWMJdXIcSGj3aqb%2FwfWam9AjvPtQKSoyCftP3P%2FkGP+U6gPe8KpIvCfS5MSYx36gkVwW5MPxkkqk%2FTFas2aNCG1OARQQgCsrk3GQOv0htmg2TFVbwhYZlUvbL7SJAZlaehS0y65YVraSx4LEfIbBsaUi+ozXe+U8vNCuqZGpdqJKXSxUOvKBI%2F082P32zZumE2THawJxlbXepWpOn5FNFRaW7vktgm1aIfp%2F7L3yg%3D%3D' and @alt = 'workout-image']</value>
      <webElementGuid>c39d648b-22b4-483f-98bf-73851f46697c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
