<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Password</name>
   <tag></tag>
   <elementGuidId>1cb55576-60d7-4952-b1e7-eb146fce42ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/form/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2aaa3042-e1a8-406b-a566-0051d221739d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3dd30a47-7162-4c8b-988b-9f2b5492214e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 block text-sm font-medium text-gray-900</value>
      <webElementGuid>77162706-39d1-4631-9c6a-137a4e1a3d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>e1562a55-e7f1-42c3-b57e-ddd00ac27489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;z-[3] max-h-full w-full bg-cover bg-no-repeat md:fixed md:h-screen&quot;]/div[@class=&quot;container z-[1] overflow-y-auto py-5&quot;]/div[@class=&quot;inset-x-5 mx-auto&quot;]/div[@class=&quot;lg:m-auto&quot;]/div[@class=&quot;border-1 bg-neutral rounded-20 border-gray-200 bg-neutral-background bg-opacity-80 p-4 shadow-6 backdrop-blur-sm md:rounded-100 md:bg-opacity-90 md:p-3 lg:mx-auto lg:w-2/4&quot;]/form[@class=&quot;mx-auto mt-1 w-full lg:mt-2 lg:w-2/4&quot;]/div[@class=&quot;mb-3 lg:mb-4&quot;]/label[@class=&quot;mb-2 block text-sm font-medium text-gray-900&quot;]</value>
      <webElementGuid>e9e4135c-6410-4135-847d-48b68d010c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>61f25251-f38f-41be-9289-a8316bb16922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>78ca145c-1906-402b-867e-b591440ed74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 block text-sm font-medium text-gray-900</value>
      <webElementGuid>ad03dec5-fa72-49c2-84dc-68890d222711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>6e95fe71-ab91-4cf6-8ff6-d9b48d1594be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;z-[3] max-h-full w-full bg-cover bg-no-repeat md:fixed md:h-screen&quot;]/div[@class=&quot;container z-[1] overflow-y-auto py-5&quot;]/div[@class=&quot;inset-x-5 mx-auto&quot;]/div[@class=&quot;lg:m-auto&quot;]/div[@class=&quot;border-1 bg-neutral rounded-20 border-gray-200 bg-neutral-background bg-opacity-80 p-4 shadow-6 backdrop-blur-sm md:rounded-100 md:bg-opacity-90 md:p-3 lg:mx-auto lg:w-2/4&quot;]/form[@class=&quot;mx-auto mt-1 w-full lg:mt-2 lg:w-2/4&quot;]/div[@class=&quot;mb-3 lg:mb-4&quot;]/label[@class=&quot;mb-2 block text-sm font-medium text-gray-900&quot;]</value>
      <webElementGuid>3ceb7bb8-e12d-4033-877f-12c58480cebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fce566c8-2d9d-43a7-b2fb-eedac57aed27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0cdc4947-2cfd-43f2-89ba-8411ac4b9826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 block text-sm font-medium text-gray-900</value>
      <webElementGuid>cf107908-7ceb-4616-8947-ab9cc00865eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>65117334-2808-46ad-857c-8a40c0b1a28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;z-[3] max-h-full w-full bg-cover bg-no-repeat md:fixed md:h-screen&quot;]/div[@class=&quot;container z-[1] overflow-y-auto py-5&quot;]/div[@class=&quot;inset-x-5 mx-auto&quot;]/div[@class=&quot;lg:m-auto&quot;]/div[@class=&quot;border-1 bg-neutral rounded-20 border-gray-200 bg-neutral-background bg-opacity-80 p-4 shadow-6 backdrop-blur-sm md:rounded-100 md:bg-opacity-90 md:p-3 lg:mx-auto lg:w-2/4&quot;]/form[@class=&quot;mx-auto mt-1 w-full lg:mt-2 lg:w-2/4&quot;]/div[@class=&quot;mb-3 lg:mb-4&quot;]/label[@class=&quot;mb-2 block text-sm font-medium text-gray-900&quot;]</value>
      <webElementGuid>69fa3788-8327-49bc-bf49-c0d6a25890ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/form/div[2]/label</value>
      <webElementGuid>a663a18b-36ca-4440-8fe7-3f0972ef2272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::label[1]</value>
      <webElementGuid>65446600-cc85-4edb-9fe5-5fc06b819ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome Back Admin!'])[1]/following::label[2]</value>
      <webElementGuid>dd2444f5-f528-4a72-ba76-9701a57c9c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::label[1]</value>
      <webElementGuid>6eb9e336-e74e-4858-b527-d59b9cfba4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright @ 2022 WorkFit.'])[1]/preceding::label[1]</value>
      <webElementGuid>11dad306-cb7c-48e8-bee5-ade5bf1d5061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password']/parent::*</value>
      <webElementGuid>8230928b-1aa1-4df5-b33b-1134555c9c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>30f1cf18-50d3-4cb3-bcca-50fbd759a18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Password' or . = 'Password')]</value>
      <webElementGuid>a4febafe-8604-4fd6-ad94-56bc2ffdfed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
