<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Yoga_fi fi-sr-play text-4xl text-white</name>
   <tag></tag>
   <elementGuidId>9f8a37cc-9e98-4b4a-8e88-f1318d246d04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fi.fi-sr-play.text-4xl.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e8ea335d-8225-433c-8a49-ff4754e224d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi fi-sr-play text-4xl text-white</value>
      <webElementGuid>720f6298-f00c-4898-aa85-cf1cdcd7f0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 sm:pl-52 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[1]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 md:grid-cols-2 md:gap-6 xl:grid-cols-3 2xl:grid-cols-4&quot;]/div[1]/div[@class=&quot;h-full rounded-20 bg-white shadow-4&quot;]/div[@class=&quot;relative overflow-hidden pb-48&quot;]/div[@class=&quot;player-wrapper&quot;]/div[@class=&quot;video-player&quot;]/div[@class=&quot;react-player__preview&quot;]/button[1]/i[@class=&quot;fi fi-sr-play text-4xl text-white&quot;]</value>
      <webElementGuid>0948d92e-e3f6-46a6-9bb3-6690d2806375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/button/i</value>
      <webElementGuid>e8048c44-d2b7-4018-a11f-04294f8a4939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/button/i</value>
      <webElementGuid>d1c29b7a-fe97-4969-9bab-5e616f426210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
