<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video</name>
   <tag></tag>
   <elementGuidId>a0603064-1e88-481e-90e8-10312f80ab8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/video</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>d66b3a37-7078-467c-a8f6-412df00bf923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/alterra-capstone.appspot.com/online-class-video/490174b7da02421293c23857438b564a.mp4?Expires=1702635063&amp;GoogleAccessId=firebase-adminsdk-kae8m%40alterra-capstone.iam.gserviceaccount.com&amp;Signature=doVC70UBlDVNAhFDUbeuVOIljrws+twbkEmlbmrYsVkScZJLosw9Gk9OsPlgrl%2Fnfy6Fydu7jEpCVkUyk15ihexb5dR4x8aoykskwFo7+EccJEL1rokR9BO5Dz%2FyK2n+XXaizvezGbXcOsmtaXMaHDqnpMzgD6oeJxXeIDemCTmZTIwKrYqe1PwZ6p+ssQv4Ri0tFXaj8cTPuSTnetG4GA6tvGw9srkJVnrSz3S6rokhRDObB1e5Pq6hhBVzPHaNOrrF%2F9LBfgmy1egy1cvJmnHeqmrfUO0INzTw+zqmMxgfmyR2JOKwQi44IzTODgV9c7mKqtvEGXS37OYg7YtX0Q%3D%3D</value>
      <webElementGuid>5681bf8d-61f0-4661-8bfc-c7355459c7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>87b4ce9f-aaec-4116-b5f0-f2262e2b0f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 sm:pl-52 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[1]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 md:grid-cols-2 md:gap-6 xl:grid-cols-3 2xl:grid-cols-4&quot;]/div[1]/div[@class=&quot;h-full rounded-20 bg-white shadow-4&quot;]/div[@class=&quot;relative overflow-hidden pb-48&quot;]/div[@class=&quot;player-wrapper&quot;]/div[@class=&quot;video-player&quot;]/video[1]</value>
      <webElementGuid>10d874a1-ae4b-4bfd-a299-963f431e9a20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/video</value>
      <webElementGuid>2d102832-9794-4d07-8f7a-4568991135fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>60b90c8e-7d78-4e7d-a044-f5e1911a73df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'https://storage.googleapis.com/alterra-capstone.appspot.com/online-class-video/490174b7da02421293c23857438b564a.mp4?Expires=1702635063&amp;GoogleAccessId=firebase-adminsdk-kae8m%40alterra-capstone.iam.gserviceaccount.com&amp;Signature=doVC70UBlDVNAhFDUbeuVOIljrws+twbkEmlbmrYsVkScZJLosw9Gk9OsPlgrl%2Fnfy6Fydu7jEpCVkUyk15ihexb5dR4x8aoykskwFo7+EccJEL1rokR9BO5Dz%2FyK2n+XXaizvezGbXcOsmtaXMaHDqnpMzgD6oeJxXeIDemCTmZTIwKrYqe1PwZ6p+ssQv4Ri0tFXaj8cTPuSTnetG4GA6tvGw9srkJVnrSz3S6rokhRDObB1e5Pq6hhBVzPHaNOrrF%2F9LBfgmy1egy1cvJmnHeqmrfUO0INzTw+zqmMxgfmyR2JOKwQi44IzTODgV9c7mKqtvEGXS37OYg7YtX0Q%3D%3D']</value>
      <webElementGuid>680ddedf-31f7-48f8-a6b3-2943718fb222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
