<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_19 Des 2022 (22.28) - 17 Feb 2023 (22.2_3a0be8</name>
   <tag></tag>
   <elementGuidId>7452ad02-48d5-49d4-9072-3d208bdc00fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[5]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>77e98765-79ef-463b-a644-226a2de16633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative rounded-20 border bg-white py-4 shadow-4</value>
      <webElementGuid>d2e6dce6-39b5-49be-9e5d-75c70811a662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19 Des 2022 (22.28) - 17 Feb 2023 (22.28)PENDINGPush upPush UpRp 250.000Angeline Feliciaangel.geumyoil@gmai...Active</value>
      <webElementGuid>ec71c5f6-8324-4673-bc70-4fbb212d9237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-36 md:grid-cols-2 md:gap-6 xl:grid-cols-2 2xl:grid-cols-3&quot;]/div[5]/div[@class=&quot;relative rounded-20 border bg-white py-4 shadow-4&quot;]</value>
      <webElementGuid>c1de7608-bd59-40c7-bdb9-ba2ad0f2fcd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div[5]/div</value>
      <webElementGuid>84038564-0696-48cc-94ec-e193cf693b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[4]/following::div[2]</value>
      <webElementGuid>462644f6-6efe-43d8-9346-e1721b44d192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coba aja Update'])[1]/following::div[14]</value>
      <webElementGuid>13754378-5229-4b89-ad30-a3e63e1f2386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div</value>
      <webElementGuid>1b887dc7-d191-49fe-9589-e75026e23c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '19 Des 2022 (22.28) - 17 Feb 2023 (22.28)PENDINGPush upPush UpRp 250.000Angeline Feliciaangel.geumyoil@gmai...Active' or . = '19 Des 2022 (22.28) - 17 Feb 2023 (22.28)PENDINGPush upPush UpRp 250.000Angeline Feliciaangel.geumyoil@gmai...Active')]</value>
      <webElementGuid>f01a1574-115b-4641-a0b0-5790e31e3441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
