<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add New_absolute inset-0 h-full w-full _e9a355</name>
   <tag></tag>
   <elementGuidId>42c80804-b68a-4485-babc-aecb9884f468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4086b22-8141-417c-84ec-e5c1bf4f6f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 h-full w-full rounded-t-20 object-cover object-center transition duration-300 ease-in-out hover:scale-105</value>
      <webElementGuid>27b7b072-adb8-4807-8ef4-dc3bd92dd063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/clean-code-72e8f.appspot.com/articles/20c7385a28af40a5923e2d4de5cd56cc.jpg?Expires=1702714206&amp;GoogleAccessId=firebase-adminsdk-lenaf%40clean-code-72e8f.iam.gserviceaccount.com&amp;Signature=bDxwQYDhAKYGMf2z3gB+OJkLJLTC3bt72ofw1S0DxfAcu5a2BB5dMv%2FwO3W0aFODVnjHX062lP804w%2FPoPJZw9+NW6wRlULtFGRXDQ9wJb0KlFy55mftliFPmwr37b12WhIreMElC0a9frsz7NXS8nQUhqzo+4645n6aNQ7z6t8zmn8lE0Id76YybMncG%2Fcu1vAPwAfbxDZqssvOgivswTx19G6bs%2Fd0IlcfbWkb3h9sYEapRMt6qdaZ4QL3K1D0LJKpLFRAbKvQQqQxy+koPxFa8PcoCFreI+Jk7euGEe4FIvHI12qwwqUFkkQliE9tLAaBqTyqX14xjcxmhQJNeA%3D%3D</value>
      <webElementGuid>db3429fb-2a41-4a01-812a-8959aa654c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>20c7385a28af40a5923e2d4de5cd56cc.jpg</value>
      <webElementGuid>181b2a8b-0b22-4e6a-b115-7ec9e0473c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>16ae2a4f-8758-45b0-a0ec-d63503cd8dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 sm:pl-52 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[1]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-20 md:grid-cols-2 md:gap-6 xl:grid-cols-3 2xl:grid-cols-4&quot;]/div[@class=&quot;lazyload-wrapper&quot;]/div[@class=&quot;h-full rounded-20 bg-white shadow-4&quot;]/div[@class=&quot;relative overflow-hidden rounded-t-20 pb-40&quot;]/img[@class=&quot;absolute inset-0 h-full w-full rounded-t-20 object-cover object-center transition duration-300 ease-in-out hover:scale-105&quot;]</value>
      <webElementGuid>839d4883-8bb0-41d0-9530-db90a6f8498e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>786f22cf-d187-45ea-a920-ef22ecca2312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 h-full w-full rounded-t-20 object-cover object-center transition duration-300 ease-in-out hover:scale-105</value>
      <webElementGuid>fa451824-950a-41d8-be2e-9b6cd74515ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://storage.googleapis.com/clean-code-72e8f.appspot.com/articles/20c7385a28af40a5923e2d4de5cd56cc.jpg?Expires=1702714206&amp;GoogleAccessId=firebase-adminsdk-lenaf%40clean-code-72e8f.iam.gserviceaccount.com&amp;Signature=bDxwQYDhAKYGMf2z3gB+OJkLJLTC3bt72ofw1S0DxfAcu5a2BB5dMv%2FwO3W0aFODVnjHX062lP804w%2FPoPJZw9+NW6wRlULtFGRXDQ9wJb0KlFy55mftliFPmwr37b12WhIreMElC0a9frsz7NXS8nQUhqzo+4645n6aNQ7z6t8zmn8lE0Id76YybMncG%2Fcu1vAPwAfbxDZqssvOgivswTx19G6bs%2Fd0IlcfbWkb3h9sYEapRMt6qdaZ4QL3K1D0LJKpLFRAbKvQQqQxy+koPxFa8PcoCFreI+Jk7euGEe4FIvHI12qwwqUFkkQliE9tLAaBqTyqX14xjcxmhQJNeA%3D%3D</value>
      <webElementGuid>ac5319d1-5e01-4e47-8d2d-575f91c62375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>20c7385a28af40a5923e2d4de5cd56cc.jpg</value>
      <webElementGuid>9de77757-c63a-40bc-ae36-31a3f0277771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>a97172ef-9105-47cb-83db-f9f25e1d8701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-full overflow-y-auto&quot;]/div[@class=&quot;flex w-full flex-1 flex-col&quot;]/div[@class=&quot;pl-0 pt-14 sm:pl-52 md:pl-52 lg:pl-52&quot;]/div[@class=&quot;container mx-auto px-6&quot;]/div[2]/div[1]/div[@class=&quot;mb-6 grid grid-cols-1 gap-3 pt-20 md:grid-cols-2 md:gap-6 xl:grid-cols-3 2xl:grid-cols-4&quot;]/div[@class=&quot;lazyload-wrapper&quot;]/div[@class=&quot;h-full rounded-20 bg-white shadow-4&quot;]/div[@class=&quot;relative overflow-hidden rounded-t-20 pb-40&quot;]/img[@class=&quot;absolute inset-0 h-full w-full rounded-t-20 object-cover object-center transition duration-300 ease-in-out hover:scale-105&quot;]</value>
      <webElementGuid>1385d651-324d-4d98-8fc8-50fd0bcfdded</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/div/div/div/div/div/img</value>
      <webElementGuid>573f8688-cf24-4ac1-baaa-332a5e0b4d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='20c7385a28af40a5923e2d4de5cd56cc.jpg']</value>
      <webElementGuid>6c1807f0-0567-419a-a055-de08448690a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e368092c-d36c-46d7-a540-62cd61f93976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://storage.googleapis.com/clean-code-72e8f.appspot.com/articles/20c7385a28af40a5923e2d4de5cd56cc.jpg?Expires=1702714206&amp;GoogleAccessId=firebase-adminsdk-lenaf%40clean-code-72e8f.iam.gserviceaccount.com&amp;Signature=bDxwQYDhAKYGMf2z3gB+OJkLJLTC3bt72ofw1S0DxfAcu5a2BB5dMv%2FwO3W0aFODVnjHX062lP804w%2FPoPJZw9+NW6wRlULtFGRXDQ9wJb0KlFy55mftliFPmwr37b12WhIreMElC0a9frsz7NXS8nQUhqzo+4645n6aNQ7z6t8zmn8lE0Id76YybMncG%2Fcu1vAPwAfbxDZqssvOgivswTx19G6bs%2Fd0IlcfbWkb3h9sYEapRMt6qdaZ4QL3K1D0LJKpLFRAbKvQQqQxy+koPxFa8PcoCFreI+Jk7euGEe4FIvHI12qwwqUFkkQliE9tLAaBqTyqX14xjcxmhQJNeA%3D%3D' and @alt = '20c7385a28af40a5923e2d4de5cd56cc.jpg']</value>
      <webElementGuid>fd1e4b82-dae3-4307-8c38-3fcba9396c8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
